goRouter redirection feature for MacOS and ios version
BU-Spark/se-scdao-mobile-flutter pull request #23
Opened 2023-07-12 20:34 UTC by molly-yan

2023-07-12 23:44 UTC, IanSaucy requested changes
Great work! Just a few clarifying questions

2023-07-12 23:44 UTC, IanSaucy commented on lib/providers/auth_provider.dart
> +
Similar to what I was talking to Jason about for the 519 project. We want to verify a token when it's retrieved from the storage. I think this library will help with that. Simply verify that it has an expiration date greater than the current date (be careful with timezones) 

https://pub.dev/packages/jwt_decoder

2023-07-12 23:44 UTC, IanSaucy commented on lib/utility/shared_pref.dart
Can you remind me why we need this and the `flutter_secure_storage`? Don't both of them persist the JWT?

2023-07-13 00:17 UTC, molly-yan commented on lib/utility/shared_pref.dart
Sorry that I forgot to remove this file. I created it before learning about flutter_secure_storage.

2023-07-13 15:07 UTC, IanSaucy requested changes
one more change!

2023-07-13 15:07 UTC, IanSaucy commented on lib/providers/auth_provider.dart
> +        _loggedInStatus = Status.NotLoggedIn;
I would also clear the stored token here too.

2023-07-14 20:00 UTC, IanSaucy approved these changes
lgtm

2023-07-14 21:02 UTC, merged